2022-01-21 16:43:43,344 INFO    MainThread:4072 [wandb_setup.py:_flush():71] setting env: {}
2022-01-21 16:43:43,344 INFO    MainThread:4072 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-21 16:43:43,345 INFO    MainThread:4072 [wandb_init.py:_log_setup():371] Logging user logs to /Users/gdegournay/PycharmProjects/Udacity/MLOps/MLOps_ex/reproducible_workflow/exercices/lesson-1-machine-learning-pipelines/exercises/exercise_1/starter/wandb/run-20220121_164343-3ddayr2s/logs/debug.log
2022-01-21 16:43:43,345 INFO    MainThread:4072 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/gdegournay/PycharmProjects/Udacity/MLOps/MLOps_ex/reproducible_workflow/exercices/lesson-1-machine-learning-pipelines/exercises/exercise_1/starter/wandb/run-20220121_164343-3ddayr2s/logs/debug-internal.log
2022-01-21 16:43:43,345 INFO    MainThread:4072 [wandb_init.py:init():404] calling init triggers
2022-01-21 16:43:43,345 INFO    MainThread:4072 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-21 16:43:43,345 INFO    MainThread:4072 [wandb_init.py:init():460] starting backend
2022-01-21 16:43:43,345 INFO    MainThread:4072 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-01-21 16:43:43,369 INFO    MainThread:4072 [backend.py:ensure_launched():216] starting backend process...
2022-01-21 16:43:44,305 INFO    MainThread:4072 [backend.py:ensure_launched():221] started backend process with pid: 4083
2022-01-21 16:43:44,307 INFO    MainThread:4072 [wandb_init.py:init():469] backend started and connected
2022-01-21 16:43:44,309 INFO    MainThread:4072 [wandb_init.py:init():533] updated telemetry
2022-01-21 16:43:44,312 INFO    MainThread:4072 [wandb_init.py:init():563] communicating current version
2022-01-21 16:43:46,201 INFO    MainThread:4072 [wandb_init.py:init():568] got version response 
2022-01-21 16:43:46,201 INFO    MainThread:4072 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-21 16:43:46,510 INFO    MainThread:4072 [wandb_init.py:init():606] starting run threads in backend
2022-01-21 16:43:50,476 INFO    MainThread:4072 [wandb_run.py:_console_start():1810] atexit reg
2022-01-21 16:43:50,476 INFO    MainThread:4072 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-21 16:43:50,477 INFO    MainThread:4072 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-21 16:43:50,479 INFO    MainThread:4072 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-21 16:43:50,479 INFO    MainThread:4072 [wandb_init.py:init():633] run started, returning control to user process
2022-01-21 16:49:10,155 ERROR   MainThread:4072 [util.py:get_module():187] Error importing optional module torch
Traceback (most recent call last):
  File "/Users/gdegournay/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/wandb/util.py", line 182, in get_module
    return import_module(name)
  File "/Users/gdegournay/opt/anaconda3/envs/udacity/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'torch'
2022-01-21 17:05:17,959 INFO    MainThread:4072 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-21 17:05:17,960 INFO    MainThread:4072 [wandb_run.py:_restore():1752] restore
